# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 18:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('nature', models.CharField(max_length=10, verbose_name='Select Source Type')),
                ('contact_no', models.CharField(max_length=14, verbose_name='Contact Number')),
                ('tlocation_X', models.FloatField(blank=True, null=True, verbose_name='Current Location X-axis')),
                ('tlocation_Y', models.FloatField(blank=True, null=True, verbose_name='Current Location Y-axis')),
                ('Address', models.CharField(max_length=300)),
                ('plocation_X', models.FloatField(blank=True, null=True, verbose_name='Permanent Location X-axis')),
                ('plocation_Y', models.FloatField(blank=True, null=True, verbose_name='Permanent Location Y-axis')),
                ('time_from', models.TimeField(help_text='Format: 00:00:00', verbose_name='Time: Available from (for donation)/Needed from(for reception)')),
                ('time_to', models.TimeField(help_text='Format: 00:00:00', verbose_name='Time: Available to (for donation)/Needed to (for reception)')),
                ('date', models.DateField(help_text='Format: yyyy-mm-dd', verbose_name='Date: on blood available/needed')),
                ('last_transaction', models.DateField(help_text='Format: yyyy-mm-dd', verbose_name='Date of Last donation/reception')),
                ('group', models.CharField(max_length=3, verbose_name='Blood Group')),
                ('bags', models.IntegerField(verbose_name='Number of Blood Bags')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('country', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=60, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('city_data', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('country', models.CharField(blank=True, max_length=120, null=True)),
                ('tlocation_X', models.FloatField(blank=True, null=True, verbose_name='Current Location X-axis')),
                ('tlocation_Y', models.FloatField(blank=True, null=True, verbose_name='Current Location Y-axis')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
